
database:
  connection_string: "<inser your connection string according to postgresql documentation https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING>"

server:
  port: 8080
  token: "<Your secret>"

plotter:
  # path to directory where temporarily store images
  temp_store: "."

logger:
  verbosity: info