name:                drink-bot-api
version:             0.1.0.0
github:              "sl1depengwyn/drink-bot-api"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/drink-bot-api#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- servant
- wai
- warp
- filepath
- aeson
- microlens
- aeson-extra
- Chart
- Chart-cairo
- colour
- data-default-class
- postgresql-simple
- resource-pool
- beam-core
- beam-postgres
- beam-migrate
- text
- bytestring
- time
- containers

default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveGeneric
- GADTs
- OverloadedStrings
- FlexibleContexts 
- FlexibleInstances 
- TypeFamilies 
- TypeApplications 
- DeriveAnyClass
- StandaloneDeriving 
- TypeSynonymInstances 
- MultiParamTypeClasses

library:
  source-dirs: src

executables:
  drink-bot-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - drink-bot-api

tests:
  drink-bot-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - drink-bot-api
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
