
database:
  connection_string: "dbname='drinkdb' user='postgres' password='dateofbuyps'"

server:
  port: 8080
  token: "<Your secret>"

plotter:
  # path to directory where temporarily store images
  temp_store: "."

logger:
  verbosity: info